// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "adder": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/goby/recipes/web/design
// --out=$(GOPATH)/src/github.com/goby/recipes/web
// --version=v1.3.0

package client
